In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import json

import warnings
warnings.filterwarnings("ignore")

print('numpy version - ', np.__version__)
print('pandas version - ', pd.__version__)

numpy version -  1.21.5
pandas version -  1.4.2


In [2]:
def seriesInfo(s):
    print('index - ', s.index, type(s.index))
    print('value - ', s.values, type(s.values))
    print()
    print('data - ')
    print(s)

In [3]:
def frmInfo(df):
    print('shape - ', df.shape)
    print('size - ', df.size)
    print('ndim - ', df.ndim)
    print('row index - ', df.index, type(df.index))
    print('col index - ', df.columns, type(df.columns))
    print('values - \n', df.values, type(df.values))
    print()
    print('data - ')
    display(df)

DataFrame: row_index, 데이터 조작, 인덱스 조작
- loc[]: 라벨값 기반
- iloc[]: 정수값 기반

In [5]:
sample_frm = pd.DataFrame(np.arange(10,22).reshape(3,4),
                         index = ['row01', 'row02', 'row03'],
                         columns = ['col01', 'col02', 'col03', 'col04'])
frmInfo(sample_frm)

shape -  (3, 4)
size -  12
ndim -  2
row index -  Index(['row01', 'row02', 'row03'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col index -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

data - 


col01  col02  col03  col04
row01     10     11     12     13
row02     14     15     16     17
row03     18     19     20     21

In [7]:
print('행 인덱스를 사용하며 행 1개 선택 - ')
print('라벨기반 - ', sample_frm.loc['row01'])
print('정수기반 - ', sample_frm.iloc[0])

행 인덱스를 사용하며 행 1개 선택 - 
라벨기반 -  col01    10
col02    11
col03    12
col04    13
Name: row01, dtype: int32
정수기반 -  col01    10
col02    11
col03    12
col04    13
Name: row01, dtype: int32


In [9]:
# 행 여러개 선택
print('라벨기반 - \n', sample_frm.loc[['row01', 'row03']])
print('정수기반 - \n', sample_frm.iloc[[0,2]])

라벨기반 - 
        col01  col02  col03  col04
row01     10     11     12     13
row03     18     19     20     21
정수기반 - 
        col01  col02  col03  col04
row01     10     11     12     13
row03     18     19     20     21


In [10]:
# 범위를 지정(slicing)하여 행 여러 개 선택
print('라벨기반 - \n', sample_frm.loc['row01' : 'row03'])
print('정수기반 - \n', sample_frm.iloc[0:2])

라벨기반 - 
        col01  col02  col03  col04
row01     10     11     12     13
row02     14     15     16     17
row03     18     19     20     21
정수기반 - 
        col01  col02  col03  col04
row01     10     11     12     13
row02     14     15     16     17


In [11]:
sample_frm['col01'] > 15

row01    False
row02    False
row03     True
Name: col01, dtype: bool

In [12]:
sample_frm.loc[sample_frm['col01'] > 15 ]

col01  col02  col03  col04
row03     18     19     20     21

In [14]:
print('행 인덱스와 열 인덱스를 사용하여 행 선택 - frm.loc[행, 열]')
print('frm[열][행]')
# 문) 첫 번째 row 모든 열을 추출
print('라벨기반 - \n ', sample_frm.loc['row01', : ])
print('정수기반 - \n', sample_frm.iloc[0, : ])
print()

print('특정 컬럼을 추출 - ')
print('라벨기반 - \n ', sample_frm.loc['row01', 'col03'])
print('정수기반 - \n', sample_frm.iloc[0, [2,3] ])

행 인덱스와 열 인덱스를 사용하여 행 선택 - frm.loc[행, 열]
frm[열][행]
라벨기반 - 
  col01    10
col02    11
col03    12
col04    13
Name: row01, dtype: int32
정수기반 - 
 col01    10
col02    11
col03    12
col04    13
Name: row01, dtype: int32

특정 컬럼을 추출 - 
라벨기반 - 
  12
정수기반 - 
 col03    12
col04    13
Name: row01, dtype: int32


In [16]:
print('프레임에서 새로운 열이 아닌 행을 추가한다면 - ')
sample_frm.loc['row04'] = 0
frmInfo(sample_frm)

프레임에서 새로운 열이 아닌 행을 추가한다면 - 
shape -  (4, 4)
size -  16
ndim -  2
row index -  Index(['row01', 'row02', 'row03', 'row04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col index -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [ 0  0  0  0]]

data - 


col01  col02  col03  col04
row01     10     11     12     13
row02     14     15     16     17
row03     18     19     20     21
row04      0      0      0      0

In [17]:
print('기존 행을 복사해서 행 추가 - ')
sample_frm.loc['row05'] = sample_frm.loc['row04']
frmInfo(sample_frm)

기존 행을 복사해서 행 추가
shape -  (5, 4)
size -  20
ndim -  2
row index -  Index(['row01', 'row02', 'row03', 'row04', 'row05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col index -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [ 0  0  0  0]
 [ 0  0  0  0]]

data - 


col01  col02  col03  col04
row01     10     11     12     13
row02     14     15     16     17
row03     18     19     20     21
row04      0      0      0      0
row05      0      0      0      0

In [18]:
print('행 추가와 비슷하게 열 추가 - ') #열추가는 인덱서 X
sample_frm['col05'] = sample_frm['col04']
frmInfo(sample_frm)
sample_frm['col06'] = 10
frmInfo(sample_frm)

행 추가와 비슷하게 열 추가 - 
shape -  (5, 5)
size -  25
ndim -  2
row index -  Index(['row01', 'row02', 'row03', 'row04', 'row05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col index -  Index(['col01', 'col02', 'col03', 'col04', 'col05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [[10 11 12 13 13]
 [14 15 16 17 17]
 [18 19 20 21 21]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

data - 


col01  col02  col03  col04  col05
row01     10     11     12     13     13
row02     14     15     16     17     17
row03     18     19     20     21     21
row04      0      0      0      0      0
row05      0      0      0      0      0

shape -  (5, 6)
size -  30
ndim -  2
row index -  Index(['row01', 'row02', 'row03', 'row04', 'row05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col index -  Index(['col01', 'col02', 'col03', 'col04', 'col05', 'col06'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [[10 11 12 13 13 10]
 [14 15 16 17 17 10]
 [18 19 20 21 21 10]
 [ 0  0  0  0  0 10]
 [ 0  0  0  0  0 10]]

data - 


col01  col02  col03  col04  col05  col06
row01     10     11     12     13     13     10
row02     14     15     16     17     17     10
row03     18     19     20     21     21     10
row04      0      0      0      0      0     10
row05      0      0      0      0      0     10

In [42]:
score_data = {
    'kor': [90, 80, 79, 96, 85],
    'eng': [88, 78, 85, 93, 92],
    'math': [84, 95, 85, 94, 93]
}
score_frm = pd.DataFrame(score_data,
                        index = ['문승환', '최진형', '오한샘', '조용일', '김가영'])
score_frm

kor  eng  math
문승환   90   88    84
최진형   80   78    95
오한샘   79   85    85
조용일   96   93    94
김가영   85   92    93

위 데이터를 활용한 실습

In [43]:
#- 모든 학생의 각 과목 평균 점수를 새로운 열(average)로 추가
score_frm['average'] = np.mean(score_frm, axis = 1).round(2)
score_frm

kor  eng  math  average
문승환   90   88    84    87.33
최진형   80   78    95    84.33
오한샘   79   85    85    83.00
조용일   96   93    94    94.33
김가영   85   92    93    90.00

In [47]:
#- 최진형 학생의 영어 점수를 90점으로 수정하고 평균 점수도 다시 계산
score_frm.loc['최진형', 'eng']= 90
score_frm

score_frm['average'] = np.mean(score_frm[['kor','eng','math']], axis=1).round(2)
score_frm

kor  eng  math  average
문승환   90   88    84    87.33
최진형   80   90    95    88.33
오한샘   79   85    85    83.00
조용일   96   93    94    94.33
김가영   85   92    93    90.00

In [49]:
#- 조용일 학생의 점수를 데이터 프레임으로 추출
score_frm.loc[['조용일']]

kor  eng  math  average
조용일   96   93    94    94.33

In [50]:
#- 문승환 학생의 점수를 시리즈 타입으로 추출
score_frm.loc['문승환']

kor        90.00
eng        88.00
math       84.00
average    87.33
Name: 문승환, dtype: float64

In [52]:
#- 오한샘 학생의 국,수,영 점수를 100으로 수정하고 평균 점수도 다시 계산
score_frm.loc['오한샘', : ] = 100
score_frm['average'] = np.mean(score_frm[['kor','eng','math']], axis=1).round(2)
score_frm

kor  eng  math  average
문승환   90   88    84    87.33
최진형   80   90    95    88.33
오한샘  100  100   100   100.00
조용일   96   93    94    94.33
김가영   85   92    93    90.00

- Series and DataFrame: count()
- Series: value_counts()

In [2]:
tmp_series = pd.Series(range(10))
print('count - ', tmp_series.count())
print('len - ', len(tmp_series))
print()

tmp_series[5] = np.NaN
print('data - ', tmp_series)
print('count - ', tmp_series.count() )
print('len - ', len(tmp_series))

count -  10
len -  10

data -  0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    NaN
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64
count -  9
len -  10


In [3]:
sample_frm = pd.DataFrame(np.random.randint(5, size=(4,4)))
sample_frm

0  1  2  3
0  0  1  3  4
1  0  3  2  2
2  3  1  0  3
3  3  1  2  4

In [4]:
print('dataframe count - \n', sample_frm.count())
print('shape - ', sample_frm.shape)
print('dataframe len - \n', len(sample_frm))
print()

sample_frm.iloc[1,0] = np.NaN
sample_frm.iloc[3,0] = np.NaN
sample_frm.iloc[2,3] = np.NaN
display(sample_frm)
print()
print('dataframe count - \n ', sample_frm.count())
print('shape - ', sample_frm.shape)
print('dataframe len - \n ', len(sample_frm))

dataframe count - 
 0    4
1    4
2    4
3    4
dtype: int64
shape -  (4, 4)
dataframe len - 
 4



0  1  2    3
0  0.0  1  3  4.0
1  NaN  3  2  2.0
2  3.0  1  0  NaN
3  NaN  1  2  4.0


dataframe count - 
  0    2
1    4
2    4
3    3
dtype: int64
shape -  (4, 4)
dataframe len - 
  4


In [5]:
sample_frm[2].value_counts()

2    2
3    1
0    1
Name: 2, dtype: int64

- 타이타닉 데이터를 활용한 실습

In [10]:
import seaborn as sns
titanic_dataset = sns.load_dataset('titanic')
print('type - ', type(titanic_dataset))
print()
display(titanic_dataset.head())
print(titanic_dataset.info())

type -  <class 'pandas.core.frame.DataFrame'>



survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None


In [11]:
titanic_dataset.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [12]:
titanic_dataset['class'].value_counts()

Third     491
First     216
Second    184
Name: class, dtype: int64

In [13]:
titanic_dataset['new_col'] = 0
del titanic_dataset['new_col']

In [14]:
# 문1 age 컬럼의 값에 10살을 더한 값으로 age_by_10 컬럼 추가
# 문2 parch와 sibsp 더한 값에 1을 더해서 family_no 컬럼 추가
# 문3 새로 만든 두 개의 컬럼을 삭제- drop 원본에 적용

In [15]:
titanic_dataset['age_by_10'] = titanic_dataset['age'] + 10
titanic_dataset.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  
0    man        True  NaN  Southampton    no  False       32.0  
1  woman       False    C    Cherbourg   yes  False       48.0  
2  woman       False  NaN  Southampton   yes   True       36.0  
3  woman       False    C  Southampton   yes  False       45.0  
4    man        True  NaN  Southampton    no   True       45.0

In [16]:
titanic_dataset['family_no'] = titanic_dataset['parch'] + titanic_dataset['sibsp'] +1
titanic_dataset.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

In [17]:
# drop(label = , axis = 0(행) 1(열), inplace = )
titanic_dataset.drop(['age_by_10', 'family_no'], axis =1, inplace = True)
titanic_dataset.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [18]:
titanic_dataset.index[:10].values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [19]:
print('요금(fare)에 대한 통계 정보 확인(최대,최소,평균,합계)')
fare_series = titanic_dataset['fare']
print('max - ', fare_series.values.max())
print('min - ', fare_series.values.min())
print('mean - ', fare_series.values.mean())
print('sum - ', fare_series.values.sum())

요금(fare)에 대한 통계 정보 확인(최대,최소,평균,합계)
max -  512.3292
min -  0.0
mean -  32.204207968574636
sum -  28693.9493


In [20]:
print('선실등급(pclass == 3) 데이터만 추출하고 싶다면')

선실등급(pclass == 3) 데이터만 추출하고 싶다면


In [21]:
display(titanic_dataset[titanic_dataset['pclass']==3])

print(titanic_dataset[titanic_dataset['pclass']==3]['pclass'].value_counts())

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third   
2           1       3  female  26.0      0      0   7.9250        S  Third   
4           0       3    male  35.0      0      0   8.0500        S  Third   
5           0       3    male   NaN      0      0   8.4583        Q  Third   
7           0       3    male   2.0      3      1  21.0750        S  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
882         0       3  female  22.0      0      0  10.5167        S  Third   
884         0       3    male  25.0      0      0   7.0500        S  Third   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
888         0       3  female   NaN      1      2  23.4500        S  Third   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
2    woman       False  NaN  Southampton   yes   True  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
7    child       False  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
882  woman       False  NaN  Southampton    no   True  
884    man        True  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
888  woman       False  NaN  Southampton    no  False  
890    man        True  NaN   Queenstown    no   True  

[491 rows x 15 columns]

3    491
Name: pclass, dtype: int64


In [22]:
print('선실등급(pclass==3) sex, who 데이터만 추출하고 싶다면 - ')
display(titanic_dataset[titanic_dataset['pclass']==3][['sex','who']].head())

선실등급(pclass==3) sex, who 데이터만 추출하고 싶다면 - 


sex    who
0    male    man
2  female  woman
4    male    man
5    male    man
7    male  child

In [23]:
pclass_subset_frm = titanic_dataset[titanic_dataset['pclass']==3]
pclass_subset_frm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
2         1       3  female  26.0      0      0   7.9250        S  Third   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
2  woman       False  NaN  Southampton   yes   True  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
7  child       False  NaN  Southampton    no  False

- set_index(): 특정 열을 데이터프레임의 행 인덱스로 설정
- reset_index(): 원복

In [24]:
pclass_subset_frm.reset_index(inplace=True)
pclass_subset_frm

index  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0        0         0       3    male  22.0      1      0   7.2500        S   
1        2         1       3  female  26.0      0      0   7.9250        S   
2        4         0       3    male  35.0      0      0   8.0500        S   
3        5         0       3    male   NaN      0      0   8.4583        Q   
4        7         0       3    male   2.0      3      1  21.0750        S   
..     ...       ...     ...     ...   ...    ...    ...      ...      ...   
486    882         0       3  female  22.0      0      0  10.5167        S   
487    884         0       3    male  25.0      0      0   7.0500        S   
488    885         0       3  female  39.0      0      5  29.1250        Q   
489    888         0       3  female   NaN      1      2  23.4500        S   
490    890         0       3    male  32.0      0      0   7.7500        Q   

     class    who  adult_male deck  embark_town alive  alone  
0    Third    man        True  NaN  Southampton    no  False  
1    Third  woman       False  NaN  Southampton   yes   True  
2    Third    man        True  NaN  Southampton    no   True  
3    Third    man        True  NaN   Queenstown    no   True  
4    Third  child       False  NaN  Southampton    no  False  
..     ...    ...         ...  ...          ...   ...    ...  
486  Third  woman       False  NaN  Southampton    no   True  
487  Third    man        True  NaN  Southampton    no   True  
488  Third  woman       False  NaN   Queenstown    no  False  
489  Third  woman       False  NaN  Southampton    no  False  
490  Third    man        True  NaN   Queenstown    no   True  

[491 rows x 16 columns]

In [25]:
pclass_subset_frm.set_index('index', inplace = True)
pclass_subset_frm

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
index                                                                          
0             0       3    male  22.0      1      0   7.2500        S  Third   
2             1       3  female  26.0      0      0   7.9250        S  Third   
4             0       3    male  35.0      0      0   8.0500        S  Third   
5             0       3    male   NaN      0      0   8.4583        Q  Third   
7             0       3    male   2.0      3      1  21.0750        S  Third   
...         ...     ...     ...   ...    ...    ...      ...      ...    ...   
882           0       3  female  22.0      0      0  10.5167        S  Third   
884           0       3    male  25.0      0      0   7.0500        S  Third   
885           0       3  female  39.0      0      5  29.1250        Q  Third   
888           0       3  female   NaN      1      2  23.4500        S  Third   
890           0       3    male  32.0      0      0   7.7500        Q  Third   

         who  adult_male deck  embark_town alive  alone  
index                                                    
0        man        True  NaN  Southampton    no  False  
2      woman       False  NaN  Southampton   yes   True  
4        man        True  NaN  Southampton    no   True  
5        man        True  NaN   Queenstown    no   True  
7      child       False  NaN  Southampton    no  False  
...      ...         ...  ...          ...   ...    ...  
882    woman       False  NaN  Southampton    no   True  
884      man        True  NaN  Southampton    no   True  
885    woman       False  NaN   Queenstown    no  False  
888    woman       False  NaN  Southampton    no  False  
890      man        True  NaN   Queenstown    no   True  

[491 rows x 15 columns]

In [26]:
pclass_subset_frm.reset_index(inplace=True)
pclass_subset_frm.set_index(['index','pclass'], inplace = True)
pclass_subset_frm

survived     sex   age  sibsp  parch     fare embarked  class  \
index pclass                                                                  
0     3              0    male  22.0      1      0   7.2500        S  Third   
2     3              1  female  26.0      0      0   7.9250        S  Third   
4     3              0    male  35.0      0      0   8.0500        S  Third   
5     3              0    male   NaN      0      0   8.4583        Q  Third   
7     3              0    male   2.0      3      1  21.0750        S  Third   
...                ...     ...   ...    ...    ...      ...      ...    ...   
882   3              0  female  22.0      0      0  10.5167        S  Third   
884   3              0    male  25.0      0      0   7.0500        S  Third   
885   3              0  female  39.0      0      5  29.1250        Q  Third   
888   3              0  female   NaN      1      2  23.4500        S  Third   
890   3              0    male  32.0      0      0   7.7500        Q  Third   

                who  adult_male deck  embark_town alive  alone  
index pclass                                                    
0     3         man        True  NaN  Southampton    no  False  
2     3       woman       False  NaN  Southampton   yes   True  
4     3         man        True  NaN  Southampton    no   True  
5     3         man        True  NaN   Queenstown    no   True  
7     3       child       False  NaN  Southampton    no  False  
...             ...         ...  ...          ...   ...    ...  
882   3       woman       False  NaN  Southampton    no   True  
884   3         man        True  NaN  Southampton    no   True  
885   3       woman       False  NaN   Queenstown    no  False  
888   3       woman       False  NaN  Southampton    no  False  
890   3         man        True  NaN   Queenstown    no   True  

[491 rows x 14 columns]

In [27]:
pclass_subset_frm.index

MultiIndex([(  0, 3),
            (  2, 3),
            (  4, 3),
            (  5, 3),
            (  7, 3),
            (  8, 3),
            ( 10, 3),
            ( 12, 3),
            ( 13, 3),
            ( 14, 3),
            ...
            (875, 3),
            (876, 3),
            (877, 3),
            (878, 3),
            (881, 3),
            (882, 3),
            (884, 3),
            (885, 3),
            (888, 3),
            (890, 3)],
           names=['index', 'pclass'], length=491)

In [28]:
titanic_dataset.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

요구사항4
- 나이가 60보다 크고 선실등급이 1등급이고 성별이 여자인 데이터만 추출

In [29]:
titanic_dataset[(titanic_dataset['age'] > 60) &
                (titanic_dataset['pclass'] == 1) & 
                (titanic_dataset['sex'] == 'female')]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
275         1       1  female  63.0      1      0  77.9583        S  First   
829         1       1  female  62.0      0      0  80.0000      NaN  First   

       who  adult_male deck  embark_town alive  alone  
275  woman       False    D  Southampton   yes  False  
829  woman       False    B          NaN   yes   True

요구사항5

In [30]:
#- 승객의 평균나이
print(int(titanic_dataset['age'].mean()))

#- 여성승객의 평균나이
print(titanic_dataset['age'][titanic_dataset['sex']=='female'].mean())
print(titanic_dataset.loc[titanic_dataset['sex']=='female', 'age'].mean())

#- 1등급 선실의 여성승객의 평균나이
print(titanic_dataset['age'][(titanic_dataset['sex']=='female') & (titanic_dataset['pclass']==1)].mean())
print(titanic_dataset.loc[(titanic_dataset['pclass'] == 1)&
                         (titanic_dataset['sex'] == 'female') , 'age'].mean())

29
27.915708812260537
27.915708812260537
34.61176470588235
34.61176470588235


정렬
- sort_index(axis = , ascending = )
- sort_values(by = , ascending = ) : 열 값을 기준으로 행 정렬

요구사항 6

In [31]:
print('타이타닉에서 승객의 나이를 기준으로 내림차순 정렬 - ')
display(titanic_dataset.sort_values(by = 'age', ascending = False))

titanic_age_subset_frm = titanic_dataset.sort_values(by = 'age', ascending = False)
titanic_age_subset_frm.reset_index(inplace = True)
display(titanic_age_subset_frm)
print()

titanic_age_subset_frm.drop('index', axis = 1, inplace = True)
display(titanic_age_subset_frm)

타이타닉에서 승객의 나이를 기준으로 내림차순 정렬 - 


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
630         1       1    male  80.0      0      0  30.0000        S  First   
851         0       3    male  74.0      0      0   7.7750        S  Third   
493         0       1    male  71.0      0      0  49.5042        C  First   
96          0       1    male  71.0      0      0  34.6542        C  First   
116         0       3    male  70.5      0      0   7.7500        Q  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
859         0       3    male   NaN      0      0   7.2292        C  Third   
863         0       3  female   NaN      8      2  69.5500        S  Third   
868         0       3    male   NaN      0      0   9.5000        S  Third   
878         0       3    male   NaN      0      0   7.8958        S  Third   
888         0       3  female   NaN      1      2  23.4500        S  Third   

       who  adult_male deck  embark_town alive  alone  
630    man        True    A  Southampton   yes   True  
851    man        True  NaN  Southampton    no   True  
493    man        True  NaN    Cherbourg    no   True  
96     man        True    A    Cherbourg    no   True  
116    man        True  NaN   Queenstown    no   True  
..     ...         ...  ...          ...   ...    ...  
859    man        True  NaN    Cherbourg    no   True  
863  woman       False  NaN  Southampton    no  False  
868    man        True  NaN  Southampton    no   True  
878    man        True  NaN  Southampton    no   True  
888  woman       False  NaN  Southampton    no  False  

[891 rows x 15 columns]

index  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0      630         1       1    male  80.0      0      0  30.0000        S   
1      851         0       3    male  74.0      0      0   7.7750        S   
2      493         0       1    male  71.0      0      0  49.5042        C   
3       96         0       1    male  71.0      0      0  34.6542        C   
4      116         0       3    male  70.5      0      0   7.7500        Q   
..     ...       ...     ...     ...   ...    ...    ...      ...      ...   
886    859         0       3    male   NaN      0      0   7.2292        C   
887    863         0       3  female   NaN      8      2  69.5500        S   
888    868         0       3    male   NaN      0      0   9.5000        S   
889    878         0       3    male   NaN      0      0   7.8958        S   
890    888         0       3  female   NaN      1      2  23.4500        S   

     class    who  adult_male deck  embark_town alive  alone  
0    First    man        True    A  Southampton   yes   True  
1    Third    man        True  NaN  Southampton    no   True  
2    First    man        True  NaN    Cherbourg    no   True  
3    First    man        True    A    Cherbourg    no   True  
4    Third    man        True  NaN   Queenstown    no   True  
..     ...    ...         ...  ...          ...   ...    ...  
886  Third    man        True  NaN    Cherbourg    no   True  
887  Third  woman       False  NaN  Southampton    no  False  
888  Third    man        True  NaN  Southampton    no   True  
889  Third    man        True  NaN  Southampton    no   True  
890  Third  woman       False  NaN  Southampton    no  False  

[891 rows x 16 columns]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           1       1    male  80.0      0      0  30.0000        S  First   
1           0       3    male  74.0      0      0   7.7750        S  Third   
2           0       1    male  71.0      0      0  49.5042        C  First   
3           0       1    male  71.0      0      0  34.6542        C  First   
4           0       3    male  70.5      0      0   7.7500        Q  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
886         0       3    male   NaN      0      0   7.2292        C  Third   
887         0       3  female   NaN      8      2  69.5500        S  Third   
888         0       3    male   NaN      0      0   9.5000        S  Third   
889         0       3    male   NaN      0      0   7.8958        S  Third   
890         0       3  female   NaN      1      2  23.4500        S  Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True    A  Southampton   yes   True  
1      man        True  NaN  Southampton    no   True  
2      man        True  NaN    Cherbourg    no   True  
3      man        True    A    Cherbourg    no   True  
4      man        True  NaN   Queenstown    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN    Cherbourg    no   True  
887  woman       False  NaN  Southampton    no  False  
888    man        True  NaN  Southampton    no   True  
889    man        True  NaN  Southampton    no   True  
890  woman       False  NaN  Southampton    no  False  

[891 rows x 15 columns]

요구사항 7

In [32]:
print('타이타닉에서 성별의 인원수 내림차순 정렬 - ', titanic_dataset['sex'].value_counts().sort_values(ascending=False))
print('타이타닉에서 나이별 인원수 내림차순 정렬 - ',titanic_dataset['age'].value_counts().sort_values(ascending=False))
print('타이타닉에서 선실별 인원수 내림차순 정렬 - ',titanic_dataset['pclass'].value_counts().sort_values(ascending=False))
print('타이타닉에서 사망/생존별 인원수 내림차순 정렬 - ', titanic_dataset['alive'].value_counts().sort_values(ascending=False))

타이타닉에서 성별의 인원수 내림차순 정렬 -  male      577
female    314
Name: sex, dtype: int64
타이타닉에서 나이별 인원수 내림차순 정렬 -  24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
66.00     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: age, Length: 88, dtype: int64
타이타닉에서 선실별 인원수 내림차순 정렬 -  3    491
1    216
2    184
Name: pclass, dtype: int64
타이타닉에서 사망/생존별 인원수 내림차순 정렬 -  no     549
yes    342
Name: alive, dtype: int64


요구사항 8

In [35]:
print('승객 나이를 기준으로 내림차순 정렬하고 순위를 부여한다면 - ')
titanic_dataset.sort_values(by = 'age', ascending = False)['age'].rank(ascending = True)

승객 나이를 기준으로 내림차순 정렬하고 순위를 부여한다면 - 


630    714.0
851    713.0
493    711.5
96     711.5
116    710.0
       ...  
859      NaN
863      NaN
868      NaN
878      NaN
888      NaN
Name: age, Length: 891, dtype: float64

In [34]:
titanic_dataset.sort_values(by = 'rank', ascending = True).head()

KeyError: 'rank'

In [141]:
sample_frm = pd.read_csv('./data/pandas_data/year2020_baby_name.csv',
                        sep = ',')
print('type - ', type(sample_frm))
print(sample_frm.info())
display(sample_frm.head())

type -  <class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33838 entries, 0 to 33837
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAME    33838 non-null  object
 1   GENDER  33838 non-null  object
 2   COUNT   33838 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 793.2+ KB
None


NAME GENDER  COUNT
0  Isabella      F  22731
1    Sophia      F  20477
2      Emma      F  17179
3    Olivia      F  16860
4       Ava      F  15300

In [143]:
sort_frm = sample_frm.sort_values(by='COUNT', ascending=False)
sort_frm.head()

NAME GENDER  COUNT
0      Isabella      F  22731
19698     Jacob      M  21875
1        Sophia      F  20477
19699     Ethan      M  17866
2          Emma      F  17179

In [144]:
sort_frm.reset_index(inplace = True)
sort_frm.drop(['index'], axis = 1, inplace = True)
sort_frm

NAME GENDER  COUNT
0      Isabella      F  22731
1         Jacob      M  21875
2        Sophia      F  20477
3         Ethan      M  17866
4          Emma      F  17179
...         ...    ...    ...
33833  Mccauley      F      5
33834     Mazal      F      5
33835    Mayzee      F      5
33836    Maythe      F      5
33837     Zzyzx      M      5

[33838 rows x 3 columns]

In [145]:
m_gender_frm = sort_frm[sort_frm['GENDER'] == 'M']
f_gender_frm = sort_frm[sort_frm['GENDER'] == 'F']

In [146]:
m_gender_frm.head()

NAME GENDER  COUNT
1    Jacob      M  21875
3    Ethan      M  17866
5  Michael      M  17133
6   Jayden      M  17030
7  William      M  16870

In [147]:
f_gender_frm.head()

NAME GENDER  COUNT
0   Isabella      F  22731
2     Sophia      F  20477
4       Emma      F  17179
8     Olivia      F  16860
14       Ava      F  15300