In [5]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import json

import warnings
warnings.filterwarnings("ignore")

print('numpy version - ', np.__version__)
print('pandas version - ', pd.__version__)

numpy version -  1.21.5
pandas version -  1.4.2


In [6]:
def seriesInfo(s):
    print('index - ', s.index, type(s.index))
    print('value - ', s.values, type(s.values))
    print()
    print('data - ')
    print(s)

In [7]:
def frmInfo(df):
    print('shape - ', df.shape)
    print('size - ', df.size)
    print('ndim - ', df.ndim)
    print('row index - ', df.index, type(df.index))
    print('col index - ', df.columns, type(df.columns))
    print('values - \n', df.values, type(df.values))
    print()
    print('data - ')
    display(df)

파일입출력과 병합, 문자열 관련된 데이터 조작
- csv, excel, json, html, scraping 비정형 파일의 종류
- read_xxxx(), to_xxxx()

In [6]:
file_path = './data/pandas_data/read_csv_sample.csv'
sample_frm = pd.read_csv(file_path)
print('type - ', type(sample_frm))
frmInfo(sample_frm)

type -  <class 'pandas.core.frame.DataFrame'>
shape -  (3, 5)
size -  15
ndim -  2
row index -  RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
col index -  Index(['c0', 'c1', 'c2', 'c3', 'c4'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values - 
 [[0 1 4 7 6]
 [1 2 5 8 4]
 [2 3 6 9 2]] <class 'numpy.ndarray'>

data - 


c0  c1  c2  c3  c4
0   0   1   4   7   6
1   1   2   5   8   4
2   2   3   6   9   2

In [7]:
sample_frm = pd.read_csv(file_path, index_col = 'c4')
print('type - ', type(sample_frm))
frmInfo(sample_frm)

type -  <class 'pandas.core.frame.DataFrame'>
shape -  (3, 4)
size -  12
ndim -  2
row index -  Int64Index([6, 4, 2], dtype='int64', name='c4') <class 'pandas.core.indexes.numeric.Int64Index'>
col index -  Index(['c0', 'c1', 'c2', 'c3'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values - 
 [[0 1 4 7]
 [1 2 5 8]
 [2 3 6 9]] <class 'numpy.ndarray'>

data - 


c0  c1  c2  c3
c4                
6    0   1   4   7
4    1   2   5   8
2    2   3   6   9

In [9]:
file_path = './data/pandas_data/남북한발전전력량.xlsx'
sample_frm = pd.read_excel(file_path)
print('type - ', type(sample_frm))
frmInfo(sample_frm)

type -  <class 'pandas.core.frame.DataFrame'>
shape -  (9, 29)
size -  261
ndim -  2
row index -  RangeIndex(start=0, stop=9, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
col index -  Index(['전력량 (억㎾h)', '발전 전력별', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values - 
 [['남한' '합계' 1077 1186 1310 1444 1650 1847 2055 2244 2153 2393 2664 2852
  3065 3225 3421 3646 3812 4031 4224 4336 4747 4969 5096 5171 5220 5281
  5404]
 [nan '수력' 64 51 49 60 41 55 52 54 61 61 56 42 53 69 59 52 52 50 56 56 65
  78 77 84 78 58 66]
 [nan '화력' 484 573 696 803 1022 1122 1264 1420 1195 1302 1518 1689 1821
  1859 2056 2127 2272 2551 2658 2802 3196 3343 3430 3581 3427 3402 3523]
 [nan '원자력' 529 563 565 581 587 670 739 771 897 1031 1090 1121 1191 1297

전력량 (억㎾h) 발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...  2007  \
0        남한     합계  1077  1186  1310  1444  1650  1847  2055  2244  ...  4031   
1       NaN     수력    64    51    49    60    41    55    52    54  ...    50   
2       NaN     화력   484   573   696   803  1022  1122  1264  1420  ...  2551   
3       NaN    원자력   529   563   565   581   587   670   739   771  ...  1429   
4       NaN    신재생     -     -     -     -     -     -     -     -  ...     -   
5        북한     합계   277   263   247   221   231   230   213   193  ...   236   
6       NaN     수력   156   150   142   133   138   142   125   107  ...   133   
7       NaN     화력   121   113   105    88    93    88    88    86  ...   103   
8       NaN    원자력     -     -     -     -     -     -     -     -  ...     -   

   2008  2009  2010  2011  2012  2013  2014  2015  2016  
0  4224  4336  4747  4969  5096  5171  5220  5281  5404  
1    56    56    65    78    77    84    78    58    66  
2  2658  2802  3196  3343  3430  3581  3427  3402  3523  
3  1510  1478  1486  1547  1503  1388  1564  1648  1620  
4     -     -     -     -    86   118   151   173   195  
5   255   235   237   211   215   221   216   190   239  
6   141   125   134   132   135   139   130   100   128  
7   114   110   103    79    80    82    86    90   111  
8     -     -     -     -     -     -     -     -     -  

[9 rows x 29 columns]

In [10]:
file_path = './data/pandas_data/read_json_sample.json'
sample_frm = pd.read_json(file_path)
print('type - ', type(sample_frm))
frmInfo(sample_frm)

type -  <class 'pandas.core.frame.DataFrame'>
shape -  (3, 4)
size -  12
ndim -  2
row index -  Index(['pandas', 'NumPy', 'matplotlib'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col index -  Index(['name', 'year', 'developer', 'opensource'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values - 
 [['' 2008 'Wes Mckinneye' 'True']
 ['' 2006 'Travis Oliphant' 'True']
 ['' 2003 'John D. Hunter' 'True']] <class 'numpy.ndarray'>

data - 


name  year        developer opensource
pandas           2008    Wes Mckinneye       True
NumPy            2006  Travis Oliphant       True
matplotlib       2003   John D. Hunter       True

In [18]:
file_path = './data/pandas_data/sample.html'
sample_tables = pd.read_html(file_path)
print('type - ', type(sample_tables))
print('len - ', len(sample_tables))
print()
for idx in range(len(sample_tables)):
    print('table index - ', idx)
    print(sample_tables[idx])

sample_frm = sample_tables[1]
print('type - ', type(sample_frm))
sample_frm.set_index('name', inplace = True)
print(sample_frm)

type -  <class 'list'>
len -  2

table index -  0
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9
table index -  1
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True


- scraping 통한 데이터 로딩
- BeautifulSoup(정적페이지)

In [20]:
from bs4 import BeautifulSoup
import requests
import re

In [23]:
response = requests.get('https://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds')
print('response code - ', response)
print()
print('response - ', response.text)

response code -  <Response [200]>
response -  <!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">
<head>
<meta charset="UTF-8"/>
<title>List of American exchange-traded funds - Wikipedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"4cb8f908-cae8-46c2-b0cf-fb063a80bba3","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_American_exchange-traded_funds","wgTitle":"List of American exchange-traded funds","wgCurRevisionId":1118854388,"wgRevisionId":1118854388,"wgArticleId":16294432,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description

In [24]:
soup = BeautifulSoup(response.text)
soup

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of American exchange-traded funds - Wikipedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"4cb8f908-cae8-46c2-b0cf-fb063a80bba3","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_American_exchange-traded_funds","wgTitle":"List of American exchange-traded funds","wgCurRevisionId":1118854388,"wgRevisionId":1118854388,"wgArticleId":16294432,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidat

In [25]:
soup.select('div > ul > li')

[<li class="toclevel-1 tocsection-1"><a href="#Stock_ETFs"><span class="tocnumber">1</span> <span class="toctext">Stock ETFs</span></a>
 <ul>
 <li class="toclevel-2 tocsection-2"><a href="#Broad_market_ETFs"><span class="tocnumber">1.1</span> <span class="toctext">Broad market ETFs</span></a></li>
 <li class="toclevel-2 tocsection-3"><a href="#Index-tracking_ETFs"><span class="tocnumber">1.2</span> <span class="toctext">Index-tracking ETFs</span></a></li>
 <li class="toclevel-2 tocsection-4"><a href="#Style_ETFs"><span class="tocnumber">1.3</span> <span class="toctext">Style ETFs</span></a>
 <ul>
 <li class="toclevel-3 tocsection-5"><a href="#Large-cap_ETFs"><span class="tocnumber">1.3.1</span> <span class="toctext">Large-cap ETFs</span></a></li>
 <li class="toclevel-3 tocsection-6"><a href="#Mid-cap_ETFs"><span class="tocnumber">1.3.2</span> <span class="toctext">Mid-cap ETFs</span></a></li>
 <li class="toclevel-3 tocsection-7"><a href="#Small-cap_ETFs"><span class="tocnumber">1.3.3</

In [30]:
print('type - ', type(soup.select('div > ul > li')))

lst = soup.select('div > ul > li')
for row in lst :
#     print(row.text)
    etf_name = re.findall('^(.*) \(NYSE', row.text)
#     print(etf_name)
#     print()
    etf_market = re.findall('NYSE Arca\|(.*)\)', row.text)
    print(etf_market)

type -  <class 'bs4.element.ResultSet'>
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['iShares Core S&P Total US Stock Mkt']
[]
['iShares Russell 3000 Index']
['Schwab US Broad Market ETF']
['Schwab Fundamental U.S. Broad Market Index ETF']
['Vanguard Total World Stock']
['Vanguard Total Stock Market']
['Vanguard Total International Stock']
['Vanguard Russell 3000']
['DIAMONDS Trust, Series 1']
['Guggenheim S&P 500 Equal Weight']
['iShares S&P Global 100 Index']
['iShares S&P 500 Index']
['SPDR S&P 500']
['SPDR Gender Diversity']
['Vanguard S&P 500']
['iShares Russell 2000 Index']
['iShares S&P 100 Index']
[]
['Guggenheim Multi-Asset Income']
['Guggenheim S&P 500 Pure Growth ETF']
['Guggenheim S&P 500 Pure Value ETF']
['iShares Russell 1000 Index']
['iShares S&P 500 Index']
['PowerShares Buyback Achievers']
['PowerShares FTSE RAFI US 1000']
['PowerShares S&P 500 Low Volatility']
['Schwab US Large-Cap ETF']
['Schwab US Dividend Equity ETF']
['Schwab Fundamental U.S. Large Company Index ETF']
['SPDR S&

- google 지오코딩 API
- conda install -c conda-forge googlemaps

In [2]:
import googlemaps
maps = googlemaps.Client(key = 'AIzaSyDdki495w62u7ziBMaVuzyYf4n-VZ8tsGA')
location = maps.geocode('서울시청')
print('location - ', type(location))
print()
print('location - ', location[0].get('geometry'))


 API queries_quota: 60 

location -  <class 'list'>

location -  {'bounds': {'northeast': {'lat': 37.7017495, 'lng': 127.1835899}, 'southwest': {'lat': 37.4259627, 'lng': 126.7645827}}, 'location': {'lat': 37.566535, 'lng': 126.9779692}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.7017495, 'lng': 127.1835899}, 'southwest': {'lat': 37.4259627, 'lng': 126.7645827}}}


실습
- 문) places = ['서울시청', '해운대해수욕장', '국립대전현충원', '한라산', '인천국제공항']
- 제공된 위치에 해당하는 위도, 경도를 추출하고 데이터 프레임을 작성해보자

In [3]:
places = ['서울시청', '해운대해수욕장', '국립대전현충원', '한라산', '인천국제공항']
lat = []
lng = []

for place in places :
    print(place)
    location = maps.geocode(place)
    lat.append(location[0].get('geometry')['location']['lat'])
    lng.append(location[0].get('geometry')['location']['lng'])
print()
print('lat - ', lat)
print('lng - ', lng)

서울시청
해운대해수욕장
국립대전현충원
한라산
인천국제공항

lat -  [37.566535, 35.1586975, 36.3686021, 33.3616666, 37.4601908]
lng -  [126.9779692, 129.1603842, 127.296685, 126.5291666, 126.4406957]


In [8]:
location_frm = pd.DataFrame({
    '위도': lat,
    '경도': lng
},
index = places)
location_frm

위도          경도
서울시청     37.566535  126.977969
해운대해수욕장  35.158698  129.160384
국립대전현충원  36.368602  127.296685
한라산      33.361667  126.529167
인천국제공항   37.460191  126.440696

In [9]:
location_frm.to_csv('./data/pandas_data/googlemaps.csv')

In [11]:
sample_frm = pd.read_csv('./data/pandas_data/googlemaps.csv')
frmInfo(sample_frm)

shape -  (5, 3)
size -  15
ndim -  2
row index -  RangeIndex(start=0, stop=5, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
col index -  Index(['Unnamed: 0', '위도', '경도'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values - 
 [['서울시청' 37.566535 126.9779692]
 ['해운대해수욕장' 35.1586975 129.1603842]
 ['국립대전현충원' 36.3686021 127.296685]
 ['한라산' 33.3616666 126.5291666]
 ['인천국제공항' 37.4601908 126.4406957]] <class 'numpy.ndarray'>

data - 


Unnamed: 0         위도          경도
0       서울시청  37.566535  126.977969
1    해운대해수욕장  35.158698  129.160384
2    국립대전현충원  36.368602  127.296685
3        한라산  33.361667  126.529167
4     인천국제공항  37.460191  126.440696

In [12]:
sample_frm.rename(columns={'Unnamed: 0': '위치'}, inplace = True)

In [13]:
sample_frm.set_index('위치', inplace=True)

In [14]:
sample_frm

위도          경도
위치                            
서울시청     37.566535  126.977969
해운대해수욕장  35.158698  129.160384
국립대전현충원  36.368602  127.296685
한라산      33.361667  126.529167
인천국제공항   37.460191  126.440696

프레임 병합
- pd.merge(): 공통의 열을 기준으로 병합
- frm.join(): 인덱스 기준으로 병합
- concat(): 연결

In [17]:
data01 = {
    '학번': [1,2,3,4],
    '이름': ['오한샘','장수빈','김가영','조용일'],
    '학년': [2,4,1,3]
}
data02 = {
    '학번': [1,2,4,5],
    '학과': ['CS', 'AI', 'AI', 'CS'],
    '학점': [2.8, 4.5, 1.9, 3.5]
}

In [18]:
stu_frm = pd.DataFrame(data01)
major_frm = pd.DataFrame(data02)

In [19]:
stu_frm

학번   이름  학년
0   1  오한샘   2
1   2  장수빈   4
2   3  김가영   1
3   4  조용일   3

In [20]:
major_frm

학번  학과   학점
0   1  CS  2.8
1   2  AI  4.5
2   4  AI  1.9
3   5  CS  3.5

In [21]:
pd.merge(stu_frm, major_frm, how = 'inner')

학번   이름  학년  학과   학점
0   1  오한샘   2  CS  2.8
1   2  장수빈   4  AI  4.5
2   4  조용일   3  AI  1.9

In [22]:
pd.merge(stu_frm, major_frm, how = 'outer')

학번   이름   학년   학과   학점
0   1  오한샘  2.0   CS  2.8
1   2  장수빈  4.0   AI  4.5
2   3  김가영  1.0  NaN  NaN
3   4  조용일  3.0   AI  1.9
4   5  NaN  NaN   CS  3.5

- 컬럼 인덱스가 다른 경우
- 속성: left_on = , right_on = 

In [28]:
data01 = {
    '학번': [1,2,3,4],
    '이름': ['오한샘','장수빈','김가영','조용일'],
    '학년': [2,4,1,3]
}
data02 = {
    '과목코드': [1,2,4,5],
    '학과': ['CS', 'AI', 'AI', 'CS'],
    '학점': [2.8, 4.5, 1.9, 3.5]
}

In [29]:
stu_frm = pd.DataFrame(data01)
major_frm = pd.DataFrame(data02)

In [31]:
pd.merge(stu_frm, major_frm, how = 'inner', left_on = '학번', right_on = '과목코드')

학번   이름  학년  과목코드  학과   학점
0   1  오한샘   2     1  CS  2.8
1   2  장수빈   4     2  AI  4.5
2   4  조용일   3     4  AI  1.9

In [25]:
import seaborn as sns
iris_frm = sns.load_dataset('iris')
print('type - ', type(iris_frm))

type -  <class 'pandas.core.frame.DataFrame'>


In [27]:
frmInfo(iris_frm)

shape -  (150, 5)
size -  750
ndim -  2
row index -  RangeIndex(start=0, stop=150, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
col index -  Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values - 
 [[5.1 3.5 1.4 0.2 'setosa']
 [4.9 3.0 1.4 0.2 'setosa']
 [4.7 3.2 1.3 0.2 'setosa']
 [4.6 3.1 1.5 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']
 [5.4 3.9 1.7 0.4 'setosa']
 [4.6 3.4 1.4 0.3 'setosa']
 [5.0 3.4 1.5 0.2 'setosa']
 [4.4 2.9 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.4 3.7 1.5 0.2 'setosa']
 [4.8 3.4 1.6 0.2 'setosa']
 [4.8 3.0 1.4 0.1 'setosa']
 [4.3 3.0 1.1 0.1 'setosa']
 [5.8 4.0 1.2 0.2 'setosa']
 [5.7 4.4 1.5 0.4 'setosa']
 [5.4 3.9 1.3 0.4 'setosa']
 [5.1 3.5 1.4 0.3 'setosa']
 [5.7 3.8 1.7 0.3 'setosa']
 [5.1 3.8 1.5 0.3 'setosa']
 [5.4 3.4 1.7 0.2 'setosa']
 [5.1 3.7 1.5 0.4 'setosa']
 [4.6 3.6 1.0 0.2 'setosa']
 [5.1 3.3 1.7 0.5 'setosa']
 [4.8 3.4 1.9 0

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
data01 = {
    'species': ['setosa', 'virginica', 'virginica', 'versicolor'],
    'sepal_length': [5.1, 4.9, 4.7, 4.6]
}
data02 = {
    'species': ['setosa', 'setosa', 'virginica', 'verginica'],
    'sepal_width': [3.5 , 3.0, 3.2, 3.1]
}
iris01_frm = pd.DataFrame(data01)
iris02_frm = pd.DataFrame(data02)
display(iris01_frm)
print()
display(iris02_frm)

species  sepal_length
0      setosa           5.1
1   virginica           4.9
2   virginica           4.7
3  versicolor           4.6

species  sepal_width
0     setosa          3.5
1  virginica          3.0
2  virginica          3.2
3  verginica          3.1

In [29]:
#중복되는 키값이 존재하면 how 대신 on
pd.merge(iris01_frm, iris02_frm, on='species')

species  sepal_length  sepal_width
0     setosa           5.1          3.5
1  virginica           4.9          3.0
2  virginica           4.9          3.2
3  virginica           4.7          3.0
4  virginica           4.7          3.2

In [30]:
data01 = {
    'species': ['setosa', 'virginica', 'virginica', 'versicolor'],
    'sepal_length': [5.1, 4.9, 4.7, 4.6]
}
data02 = {
    'species': ['setosa', 'setosa', 'virginica', 'verginica'],
    'sepal_length': [3.5 , 3.0, 3.2, 3.1],
    'petal_width' : [3.5 , 3.0, 3.2, 3.1]
}
iris01_frm = pd.DataFrame(data01)
iris02_frm = pd.DataFrame(data02)
display(iris01_frm)
print()
display(iris02_frm)

species  sepal_length
0      setosa           5.1
1   virginica           4.9
2   virginica           4.7
3  versicolor           4.6

species  sepal_length  petal_width
0     setosa           3.5          3.5
1     setosa           3.0          3.0
2  virginica           3.2          3.2
3  verginica           3.1          3.1

In [32]:
pd.merge(iris01_frm, iris02_frm, on=['species'])

species  sepal_length_x  sepal_length_y  petal_width
0     setosa             5.1             3.5          3.5
1     setosa             5.1             3.0          3.0
2  virginica             4.9             3.2          3.2
3  virginica             4.7             3.2          3.2

- merge: 열 병합
- 인덱스를 기준으로 merge: left_index, right_index

In [33]:
sample_frm01 = pd.DataFrame({
    'city': ['seoul', 'seoul', 'seoul', 'kwangju', 'kwangju'],
    'year': [2010,2050,2020,2018,2022],
    'pop': [100,200,300,400,500]
})
sample_frm01

city  year  pop
0    seoul  2010  100
1    seoul  2050  200
2    seoul  2020  300
3  kwangju  2018  400
4  kwangju  2022  500

In [35]:
# 다중인덱스

sample_frm02 = pd.DataFrame(np.arange(12).reshape(6,2),
                           columns = ['feature01', 'feature02'],
                           index = [['seoul', 'seoul', 'kwangju', 'kwangju', 'kwangju', 'kwangju'],
                                   [2010, 2050, 2020, 2018, 2022, 2021]])
sample_frm02

feature01  feature02
seoul   2010          0          1
        2050          2          3
kwangju 2020          4          5
        2018          6          7
        2022          8          9
        2021         10         11

In [36]:
# error
# pd.merge(sample_frm01, sample_frm02, left_index= True, right_index = True)
pd.merge(sample_frm01, sample_frm02, right_index= True, left_on=['city', 'year'])


city  year  pop  feature01  feature02
0    seoul  2010  100          0          1
1    seoul  2050  200          2          3
3  kwangju  2018  400          6          7
4  kwangju  2022  500          8          9

In [37]:
data01 = {
    '학번': [1,2,3,4],
    '이름': ['오한샘','장수빈','김가영','조용일']
}
data02 = {
    '과목코드': [1,2,4,5],
    '학과': ['CS', 'AI', 'AI', 'CS']
}
stu_frm = pd.DataFrame(data01)
major_frm = pd.DataFrame(data02)

In [38]:
pd.merge(stu_frm, major_frm, left_index = True , right_index = True)

학번   이름  과목코드  학과
0   1  오한샘     1  CS
1   2  장수빈     2  AI
2   3  김가영     4  AI
3   4  조용일     5  CS

In [39]:
stu_frm.join(major_frm, how = 'inner')

학번   이름  과목코드  학과
0   1  오한샘     1  CS
1   2  장수빈     2  AI
2   3  김가영     4  AI
3   4  조용일     5  CS

- concat : 열 인덱스와 인덱스를 기준으로 하지않고 단순한 데이터 연결

In [40]:
pd.concat([pd.Series([0,1]), pd.Series([2,3,4,5])])

0    0
1    1
0    2
1    3
2    4
3    5
dtype: int64

In [42]:
pd.concat([stu_frm, major_frm], axis = 0)

학번   이름  과목코드   학과
0  1.0  오한샘   NaN  NaN
1  2.0  장수빈   NaN  NaN
2  3.0  김가영   NaN  NaN
3  4.0  조용일   NaN  NaN
0  NaN  NaN   1.0   CS
1  NaN  NaN   2.0   AI
2  NaN  NaN   4.0   AI
3  NaN  NaN   5.0   CS

In [44]:
stock_frm01 = pd.read_excel('./data/pandas_data/stock_price.xlsx')
stock_frm02 = pd.read_excel('./data/pandas_data/stock_valuation.xlsx')

In [45]:
display(stock_frm01)
print()
display(stock_frm02)

id stock_name          value   price
0  128940       한미약품   59385.666667  421000
1  130960     CJ E&M   58540.666667   98900
2  138250      엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280     녹십자엠에스     468.833333   10200
5  145990        삼양사   82750.000000   82000
6  185750        종근당   40293.666667  100500
7  192400      쿠쿠홀딩스  179204.666667  177500
8  199800         툴젠   -2514.333333  115400
9  204210     모두투어리츠    3093.333333    3475

id       name           eps     bps        per       pbr
0  130960     CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480         하림    274.166667    3551  11.489362  0.887074
2  138040    메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480        이마트  18268.166667  295780  13.931338  0.860437
4  145990        삼양사   5741.000000  108090  14.283226  0.758627
5  161390      한국타이어   5648.500000   51341   7.453306  0.820007
6  181710  NHN엔터테인먼트   2110.166667   78434  30.755864  0.827447
7  185750        종근당   3990.333333   40684  25.185866  2.470259
8  204210     모두투어리츠     85.166667    5335  40.802348  0.651359
9  207940   삼성바이오로직스   4644.166667   60099  89.790059  6.938551